fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    sudo: 'https://github.com/saz/puppet-sudo.git'
    sensu: 'https://github.com/sensu/sensu-puppet.git'
  symlinks:
    monitoring_check: "#{source_dir}"
