fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    sudo:
        repo: 'git://github.com/bobtfish/puppet-sudo.git'
        ref: 530bb59a8d593bf664868dccd0ca2e84e8ae50f9
    sensu: 'git://github.com/sensu/sensu-puppet.git'
    apt: "git://github.com/bobtfish/puppetlabs-apt.git"
  symlinks:
    monitoring_check: "#{source_dir}"
