fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    sudo:
        repo: 'git://github.com/bobtfish/puppet-sudo.git'
        ref: 530bb59a8d593bf664868dccd0ca2e84e8ae50f9
    sensu:
        repo: 'git://github.com/sensu/sensu-puppet.git'
        ref: 9ba0abf38f1a0971bcd044b1bd51b58ec95783d9
    apt:
        repo: 'git://github.com/puppetlabs/puppetlabs-apt.git'
        ref: 2.1.0
  symlinks:
    monitoring_check: "#{source_dir}"
