---
language: ruby
before_install: rm Gemfile.lock || true
rvm:
#  - 1.8.7
  - 1.9.3
script: bundle exec rake spec
env:
  matrix:
  - PUPPET_VERSION="~> 3.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes

